name: Cria Relase Alpha

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    name: Cria Relase Alpha
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Pega a data atual formatada
      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
        env:
          TZ: 'America/Sao_Paulo'

      - name: Create Alpha Dated Release
        uses: softprops/action-gh-release@v3
        with:
          # Junta o 'v-alpha', a data e o número do build (Ex: v-alpha-2026.06.28.1)
          tag_name: v-alpha-${{ steps.date.outputs.date }}.${{ github.run_number }}
          files: |
            modpacks/*
          prerelease: true

      - name: Create Latest Alpha Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v-alpha-latest
          files: |
            modpacks/*
          prerelease: true