name: Cria Relase Alpha

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    name: Cria Relase Alpha
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # Pega a data atual formatada
      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
        env:
          TZ: "America/Sao_Paulo"

      - name: Rename Modpack Files
        run: |
          mkdir -p dist
          cp "modpacks/IlhaDeEsmeralda - Admin 1.0.0.mrpack"  "dist/IlhaDeEsmeralda - Admin.mrpack"
          cp "modpacks/IlhaDeEsmeralda - Base 1.0.0.mrpack"   "dist/IlhaDeEsmeralda - Base.mrpack"
          cp "modpacks/IlhaDeEsmeralda - Client 1.0.0.mrpack" "dist/IlhaDeEsmeralda - Client.mrpack"
          cp "modpacks/IlhaDeEsmeralda - Server 1.0.0.mrpack" "dist/IlhaDeEsmeralda - Server.mrpack"

      - name: Create Alpha Dated Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v-alpha-${{ steps.date.outputs.date }}.${{ github.run_number }}
          name: "Alpha Build ${{ steps.date.outputs.date }}"
          prerelease: true
          files: dist/*

      - name: Create Latest Alpha Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v-alpha-latest
          name: "Alpha Latest"
          overwrite_files: true
          prerelease: true
          files: dist/*
          
