name: Release Modpack Alpha

on:
  push:
    tags:
      - 'alpha'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    name: Cria Alpha Modpack Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            modpacks/*
          prerelease: true